version: "3.7"
services:
  app:
    build:
      args:
        user: falcon
        uid: 501
      context: ./
      dockerfile: Dockerfile
    image: laravel6
    container_name: laravel6-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel6

  db:
    image: mysql:8.1
    container_name: laravel6-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker-compose/mysql/data:/var/lib/mysql
    networks:
      - laravel6

  nginx:
    image: nginx:1.17-alpine
    container_name: laravel6-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - laravel6

networks:
  laravel6:
    driver: bridge
